### PR TITLE
Now supports specifying a version number

### PR DESCRIPTION
**Pull request by rk295**
I'll work to fix up the issue with JQ, but in the meantime merging this would be helpful!

### CODE REVIEW

**Comment by fidian** [comment]
Can you update this pull request and take out the note about jq and versions?  jq now installs 1.5.

**Comment by rk295** [comment]
kk, on it.

**Comment by fidian** [comment]
But I wanted the `--version=...` flag to exist.  Why did you drop this commit?  Or are you making a new one?

**Comment by rk295** [comment]
Just seen this, new commit. Sorry.

**Pull request closed without merging**
