### PR TITLE
Adding args to command if existing has none

### PR DESCRIPTION
**Pull request by baelish**

### CODE REVIEW

**Comment by baelish** [comment]
This shows the wickFormula bit is doing all the right things:
```
    amazon-ebs: Adding formula rabbitmq (/home/centos/wick-project/parent/formulas/rabbitmq)
    amazon-ebs: Formula is already in list: rabbitmq
    amazon-ebs: Formula is already in list and has no arguments, adding arguments: rabbitmq
    amazon-ebs: Formula is already in list and has additional arguments: rabbitmq
    amazon-ebs: Order of formulas to execute [52]: /home/centos/wick-project/parent/formulas/rabbitmq/run --iface=tun0 --encrypt
```

**Comment by fidian** [comment]
Merged to master.

**Comment by baelish** [comment]
I'm afraid this change has a bug. When a formula has a depends file which tests for ```--options``` and the ```--options``` are provided any time other then the first time the formula is evaluated then the dependencies which only get installed because of said option don't get installed (example below). I added some code to rerun the dependencies but then the dependencies can end up being installed after the formula which depend on it. I am not sure this can be fixed without a major rewrite and I expect we can agree the benefits don't outweigh the effort so suggest we roll back to before this commit. :(

depends containing:
```
wickGetOption ENCRYPT encrypt "$@"

if [[ ! -z "$ENCRYPT" ]]; then
    wickFormula encrypt-folder
fi
```
If the formula containing this depends file is not passed the ```--encrypt``` option the first time it's added the ```encrypt-folder``` formula is likely to be installed after the formula depending on it (with the added code I tested) or not at all.

**Comment by fidian** [comment]
Reverted and added a comment to the file explaining why we can't do this.

**Pull request merged**
